include:
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-base.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-vm.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.2/gitlab-base.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.2/gitlab-vm.yml'

variables:
  qb_opts: '-o +components+app-split-browser'
